# Generated by Django 2.1.15 on 2020-06-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
