# Generated by Django 2.1.15 on 2020-06-15 04:03

import boards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_article_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=boards.models.IntegerRangeField(),
        ),
    ]
